### ISSUE TITLE
setup.py is still Python 2.0

### ISSUE THREAD

**Issue by kemerelab** [rusefi/gerbmerge#9]
Unless I missed something, setup.py is still Python 2.0? (I get the following error trying to run setup.py)

```
    ERROR: Command errored out with exit status 1:
     command: /home/ckemere/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ckemere/Code/temp/gerbmerge/setup.py'"'"'; __file__='"'"'/home/ckemere/Code/temp/gerbmerge/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i5taqek6
         cwd: /home/ckemere/Code/temp/gerbmerge/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ckemere/Code/temp/gerbmerge/setup.py", line 12
        print '*'*73
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('*'*73)?
```

**Comment by rusefillc** [comment]
@kemerelab see https://github.com/rusefi/gerbmerge/pull/10
